routes:

collections:
  /:
    permalink: /{slug}/
    template: index
  /products/:
    permalink: /products/{slug}/
    template: page-products
    data: tag.product

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
